import { Localization } from '../../models/types';
import { categoryArray } from '../start-page/categories';

export const localizationEng: Localization = {
    playerTab: 'Player',
    aboutTab: 'About',
    favoritesTab: 'Favorites',
    // tagline: 'Keep Calm & Listen To Music',
    // 'play-button': 'Play',
    // 'load-button': 'Load',
    'random-button': 'Random',
    'save-button': 'Save',
    'piano-button': 'Piano',
    'piano-lower': 'lower',
    'piano-volume': 'Volume',
    'piano-keys': 'Show Keys',
    'piano-notes': 'Show Notes',
    'piano-higher': 'higher',
    winter: 'Winter 2023',
    presets: 'Presets',
    'Above and below the Waterline': 'Above and below the Waterline',
    'City Vibes': 'City Vibes',
    'Close to Nature': 'Close to Nature',
    'Darkness Within': 'Darkness Within',
    'Meditate me': 'Meditate me',
    'Sci-fi': 'Sci-fi',
    'Weather for all': 'Weather for all',
    'Welcome to the village': 'Welcome to the village',
    water: categoryArray[0].description,
    city: categoryArray[1].description,
    nature: categoryArray[2].description,
    darkness: categoryArray[3].description,
    meditation: categoryArray[4].description,
    'science fiction': categoryArray[5].description,
    weather: categoryArray[6].description,
    village: categoryArray[7].description,
    [categoryArray[0].presets[0].presetName]: categoryArray[0].presets[0].presetName,
    [categoryArray[0].presets[1].presetName]: categoryArray[0].presets[1].presetName,
    [categoryArray[0].presets[2].presetName]: categoryArray[0].presets[2].presetName,
    [categoryArray[0].presets[3].presetName]: categoryArray[0].presets[3].presetName,
    [categoryArray[0].presets[4].presetName]: categoryArray[0].presets[4].presetName,
    [categoryArray[1].presets[0].presetName]: categoryArray[1].presets[0].presetName,
    [categoryArray[1].presets[1].presetName]: categoryArray[1].presets[1].presetName,
    [categoryArray[1].presets[2].presetName]: categoryArray[1].presets[2].presetName,
    [categoryArray[2].presets[0].presetName]: categoryArray[2].presets[0].presetName,
    [categoryArray[2].presets[1].presetName]: categoryArray[2].presets[1].presetName,
    [categoryArray[2].presets[2].presetName]: categoryArray[2].presets[2].presetName,
    [categoryArray[2].presets[3].presetName]: categoryArray[2].presets[3].presetName,
    [categoryArray[2].presets[4].presetName]: categoryArray[2].presets[4].presetName,
    [categoryArray[3].presets[0].presetName]: categoryArray[3].presets[0].presetName,
    [categoryArray[3].presets[1].presetName]: categoryArray[3].presets[1].presetName,
    [categoryArray[3].presets[2].presetName]: categoryArray[3].presets[2].presetName,
    [categoryArray[3].presets[3].presetName]: categoryArray[3].presets[3].presetName,
    [categoryArray[3].presets[4].presetName]: categoryArray[3].presets[4].presetName,
    [categoryArray[4].presets[0].presetName]: categoryArray[4].presets[0].presetName,
    [categoryArray[4].presets[1].presetName]: categoryArray[4].presets[1].presetName,
    [categoryArray[4].presets[2].presetName]: categoryArray[4].presets[2].presetName,
    [categoryArray[4].presets[3].presetName]: categoryArray[4].presets[3].presetName,
    [categoryArray[4].presets[4].presetName]: categoryArray[4].presets[4].presetName,
    [categoryArray[5].presets[0].presetName]: categoryArray[5].presets[0].presetName,
    [categoryArray[5].presets[1].presetName]: categoryArray[5].presets[1].presetName,
    [categoryArray[5].presets[2].presetName]: categoryArray[5].presets[2].presetName,
    [categoryArray[5].presets[3].presetName]: categoryArray[5].presets[3].presetName,
    [categoryArray[5].presets[4].presetName]: categoryArray[5].presets[4].presetName,
    [categoryArray[6].presets[0].presetName]: categoryArray[6].presets[0].presetName,
    [categoryArray[6].presets[1].presetName]: categoryArray[6].presets[1].presetName,
    [categoryArray[6].presets[2].presetName]: categoryArray[6].presets[2].presetName,
    [categoryArray[6].presets[3].presetName]: categoryArray[6].presets[3].presetName,
    [categoryArray[6].presets[4].presetName]: categoryArray[6].presets[4].presetName,
    [categoryArray[7].presets[0].presetName]: categoryArray[7].presets[0].presetName,
    [categoryArray[7].presets[1].presetName]: categoryArray[7].presets[1].presetName,
    [categoryArray[7].presets[2].presetName]: categoryArray[7].presets[2].presetName,
    [categoryArray[7].presets[3].presetName]: categoryArray[7].presets[3].presetName,
    [categoryArray[7].presets[4].presetName]: categoryArray[7].presets[4].presetName,
};

export const localizationRu: Localization = {
    playerTab: 'Проигрыватель',
    aboutTab: 'О приложении',
    favoritesTab: 'Любимое',
    // tagline: 'Расслабьтесь и насладитесь звуком',
    // 'play-button': 'Играть',
    // 'load-button': 'Загрузить',
    'random-button': 'Реши само!',
    'save-button': 'Сохранить',
    'piano-button': 'Пианино',
    'piano-lower': 'ниже',
    'piano-volume': 'Громкость',
    'piano-keys': 'Скрыть кнопки',
    'piano-notes': 'Скрыть ноты',
    'piano-higher': 'выше',
    winter: 'Зима 2023',
    presets: 'Пресеты',
    'Above and below the Waterline': 'Выше и ниже ватерлинии',
    'City Vibes': 'В ритме города',
    'Close to Nature': 'На лоне природы',
    'Darkness Within': 'Тьма внутри',
    'Meditate me': 'Время медитации',
    'Sci-fi': 'Научная фантастика',
    'Weather for all': 'Погода на любой вкус',
    'Welcome to the village': 'Добро пожаловать в деревню',
    water: categoryArray[0].descriptionRu,
    city: categoryArray[1].descriptionRu,
    nature: categoryArray[2].descriptionRu,
    darkness: categoryArray[3].descriptionRu,
    meditation: categoryArray[4].descriptionRu,
    'science fiction': categoryArray[5].descriptionRu,
    weather: categoryArray[6].descriptionRu,
    village: categoryArray[7].descriptionRu,
    [categoryArray[0].presets[0].presetName]: categoryArray[0].presets[0].presetNameRu,
    [categoryArray[0].presets[1].presetName]: categoryArray[0].presets[1].presetNameRu,
    [categoryArray[0].presets[2].presetName]: categoryArray[0].presets[2].presetNameRu,
    [categoryArray[0].presets[3].presetName]: categoryArray[0].presets[3].presetNameRu,
    [categoryArray[0].presets[4].presetName]: categoryArray[0].presets[4].presetNameRu,
    [categoryArray[1].presets[0].presetName]: categoryArray[1].presets[0].presetNameRu,
    [categoryArray[1].presets[1].presetName]: categoryArray[1].presets[1].presetNameRu,
    [categoryArray[1].presets[2].presetName]: categoryArray[1].presets[2].presetNameRu,
    [categoryArray[2].presets[0].presetName]: categoryArray[2].presets[0].presetNameRu,
    [categoryArray[2].presets[1].presetName]: categoryArray[2].presets[1].presetNameRu,
    [categoryArray[2].presets[2].presetName]: categoryArray[2].presets[2].presetNameRu,
    [categoryArray[2].presets[3].presetName]: categoryArray[2].presets[3].presetNameRu,
    [categoryArray[2].presets[4].presetName]: categoryArray[2].presets[4].presetNameRu,
    [categoryArray[3].presets[0].presetName]: categoryArray[3].presets[0].presetNameRu,
    [categoryArray[3].presets[1].presetName]: categoryArray[3].presets[1].presetNameRu,
    [categoryArray[3].presets[2].presetName]: categoryArray[3].presets[2].presetNameRu,
    [categoryArray[3].presets[3].presetName]: categoryArray[3].presets[3].presetNameRu,
    [categoryArray[3].presets[4].presetName]: categoryArray[3].presets[4].presetNameRu,
    [categoryArray[4].presets[0].presetName]: categoryArray[4].presets[0].presetNameRu,
    [categoryArray[4].presets[1].presetName]: categoryArray[4].presets[1].presetNameRu,
    [categoryArray[4].presets[2].presetName]: categoryArray[4].presets[2].presetNameRu,
    [categoryArray[4].presets[3].presetName]: categoryArray[4].presets[3].presetNameRu,
    [categoryArray[4].presets[4].presetName]: categoryArray[4].presets[4].presetNameRu,
    [categoryArray[5].presets[0].presetName]: categoryArray[5].presets[0].presetNameRu,
    [categoryArray[5].presets[1].presetName]: categoryArray[5].presets[1].presetNameRu,
    [categoryArray[5].presets[2].presetName]: categoryArray[5].presets[2].presetNameRu,
    [categoryArray[5].presets[3].presetName]: categoryArray[5].presets[3].presetNameRu,
    [categoryArray[5].presets[4].presetName]: categoryArray[5].presets[4].presetNameRu,
    [categoryArray[6].presets[0].presetName]: categoryArray[6].presets[0].presetNameRu,
    [categoryArray[6].presets[1].presetName]: categoryArray[6].presets[1].presetNameRu,
    [categoryArray[6].presets[2].presetName]: categoryArray[6].presets[2].presetNameRu,
    [categoryArray[6].presets[3].presetName]: categoryArray[6].presets[3].presetNameRu,
    [categoryArray[6].presets[4].presetName]: categoryArray[6].presets[4].presetNameRu,
    [categoryArray[7].presets[0].presetName]: categoryArray[7].presets[0].presetNameRu,
    [categoryArray[7].presets[1].presetName]: categoryArray[7].presets[1].presetNameRu,
    [categoryArray[7].presets[2].presetName]: categoryArray[7].presets[2].presetNameRu,
    [categoryArray[7].presets[3].presetName]: categoryArray[7].presets[3].presetNameRu,
    [categoryArray[7].presets[4].presetName]: categoryArray[7].presets[4].presetNameRu,
};
