import { Localization } from '../../models/types';

export const localizationEng: Localization = {
    playerTab: 'Player',
    aboutTab: 'About',
    favoritesTab: 'Favorites',
    tagline: 'Keep Calm & Listen To Music',
    'play-button': 'Play',
    'load-button': 'Load',
    'save-button': 'Save',
    'piano-button': 'Piano',
    'piano-lower': 'lower',
    'piano-volume': 'Volume',
    'piano-keys': 'Show Keys',
    'piano-notes': 'Show Notes',
    'piano-higher': 'higher',
    winter: 'Winter 2023',
    presets: 'Presets',
    'Above and below the Waterline': 'Above and below the Waterline',
    'City Vibes': 'City Vibes',
    'Close to Nature': 'Close to Nature',
    'Darkness Within': 'Darkness Within',
    'Meditate me': 'Meditate me',
    'Sci-fi': 'Sci-fi',
    'Weather for all': 'Weather for all',
    'Welcome to the village': 'Welcome to the village',
};

export const localizationRu: Localization = {
    playerTab: 'Проигрыватель',
    aboutTab: 'О приложении',
    favoritesTab: 'Любимое',
    tagline: 'Расслабьтесь и насладитесь звуком',
    'play-button': 'Играть',
    'load-button': 'Загрузить',
    'save-button': 'Сохранить',
    'piano-button': 'Пианино',
    'piano-lower': 'ниже',
    'piano-volume': 'Громкость',
    'piano-keys': 'Скрыть кнопки',
    'piano-notes': 'Скрыть ноты',
    'piano-higher': 'выше',
    winter: 'Зима 2023',
    presets: 'Пресеты',
    'Above and below the Waterline': 'Выше и ниже ватерлинии',
    'City Vibes': 'В ритме города',
    'Close to Nature': 'На лоне природы',
    'Darkness Within': 'Тьма внутри',
    'Meditate me': 'Время медитации',
    'Sci-fi': 'Научная фантастика',
    'Weather for all': 'Погода на любой вкус',
    'Welcome to the village': 'Добро пожаловать в деревню',
};
